# Generated by Django 5.2.8 on 2026-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_changed_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total product value / selling price', max_digits=10),
        ),
    ]
